# Generated by Django 4.2.6 on 2023-10-18 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomecargo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('rg', models.CharField(max_length=8)),
                ('cnpj', models.CharField(max_length=14)),
                ('razaosocial', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=8)),
                ('telefone1', models.CharField(max_length=15)),
                ('telefone2', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='OrdemDeServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defeitoreclamado', models.TextField()),
                ('procedimentorealizado', models.TextField()),
                ('dt_hora_entrada', models.DateTimeField()),
                ('dt_hora_saida', models.DateTimeField(blank=True, null=True)),
                ('valorservico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statusservico', models.CharField(choices=[('PARA FAZER', 'Para Fazer'), ('EM ANDAMENTO', 'Em Andamento'), ('FINALIZADO', 'Finalizado'), ('ENTREGUE', 'Entregue')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoPeca', models.CharField(max_length=100)),
                ('MarcaPeca', models.CharField(max_length=100)),
                ('ModeloPeca', models.CharField(max_length=100)),
                ('EstoqueAtual', models.PositiveIntegerField()),
                ('PrecoCompra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PrecoVendaFinal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('QtdTotalVendida', models.PositiveIntegerField()),
                ('TotalEmVendas', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoVeiculo', models.CharField(max_length=100)),
                ('PlacaVeiculo', models.CharField(max_length=20)),
                ('AnoVeiculo', models.PositiveIntegerField()),
                ('ModeloVeiculo', models.CharField(max_length=100)),
                ('Potencia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Caminhao',
            fields=[
                ('veiculo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aplic.veiculo')),
                ('capacidade', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            bases=('aplic.veiculo',),
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('veiculo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aplic.veiculo')),
                ('cavalos', models.PositiveIntegerField()),
            ],
            bases=('aplic.veiculo',),
        ),
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('veiculo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aplic.veiculo')),
                ('cilindrada', models.PositiveIntegerField()),
            ],
            bases=('aplic.veiculo',),
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorecibo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datahoraemissao', models.DateTimeField()),
                ('ordensdeservico', models.ManyToManyField(to='aplic.ordemdeservico')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorfinalservico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valorrecebido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('restante', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('anodereferencia', models.PositiveIntegerField()),
                ('totalpago', models.BooleanField(default=False)),
                ('dthorapagamento', models.DateTimeField()),
                ('formapagamento', models.CharField(max_length=50)),
                ('statuspagamento', models.CharField(choices=[('Pendente', 'Pendente'), ('Pago', 'Pago')], max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplic.pagamento'),
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomefuncionario', models.CharField(max_length=100)),
                ('cargofuncionario', models.CharField(max_length=50)),
                ('ordensdeservico', models.ManyToManyField(to='aplic.ordemdeservico')),
            ],
        ),
    ]
